Repository pgexporter/pgexporter, pull requests merged in 2025-06, with the labels that each got.

#232 Add extension format
  CMakeLists.txt
  extensions/CMakeLists.txt
  extensions/pg_stat_statements.yaml
  pgexporter.spec
  src/include/ext_query_alts.h
  src/include/extension.h
  src/include/pg_query_alts.h
  src/include/pgexporter.h
  src/include/queries.h
  src/libpgexporter/configuration.c
  src/libpgexporter/ext_query_alts.c
  src/libpgexporter/extension.c
  src/libpgexporter/json_configuration.c
  src/libpgexporter/pg_query_alts.c
  src/libpgexporter/prometheus.c
  src/libpgexporter/queries.c
  src/libpgexporter/utils.c
  src/libpgexporter/yaml_configuration.c
  src/main.c
Labels: feature

#238 [#237] Fix Memory leak in pgexporter-admin
  src/admin.c
Labels: bug

#246 Use malloc in http_get
  src/libpgexporter/http.c
  src/libpgexporter/utils.c
Labels: enhancement

#247 Add test suite
  .github/workflows/ci.yml
  CMakeLists.txt
  test/CMakeLists.txt
  test/include/tsclient.h
  test/runner.c
  test/testcases/pgexporter_test_1.c
  test/testcases/pgexporter_test_1.h
  test/testcases/pgexporter_test_2.c
  test/testcases/pgexporter_test_2.h
  test/testcases/pgexporter_test_3.c
  test/testcases/pgexporter_test_3.h
  test/testsuite.sh
  test/tsclient.c
Labels: feature

#243 [#239] Pull metrics from other databases
  contrib/json/postgresql-13.json
  contrib/json/postgresql-14.json
  contrib/json/postgresql-15.json
  contrib/json/postgresql-16.json
  contrib/json/postgresql-17.json
  contrib/yaml/postgresql-13.yaml
  contrib/yaml/postgresql-14.yaml
  contrib/yaml/postgresql-15.yaml
  contrib/yaml/postgresql-16.yaml
  contrib/yaml/postgresql-17.yaml
  doc/tutorial/02_custom_metrics.md
  src/include/internal.h
  src/include/pgexporter.h
  src/include/queries.h
  src/libpgexporter/json_configuration.c
  src/libpgexporter/network.c
  src/libpgexporter/prometheus.c
  src/libpgexporter/queries.c
  src/libpgexporter/yaml_configuration.c
Labels: feature

#257 Detect duplicate metric names
  contrib/json/postgresql-13.json
  contrib/json/postgresql-14.json
  contrib/json/postgresql-15.json
  contrib/json/postgresql-16.json
  contrib/json/postgresql-17.json
  contrib/yaml/postgresql-13.yaml
  contrib/yaml/postgresql-14.yaml
  contrib/yaml/postgresql-15.yaml
  contrib/yaml/postgresql-16.yaml
  contrib/yaml/postgresql-17.yaml
  src/include/internal.h
  src/include/pgexporter.h
  src/include/utils.h
  src/libpgexporter/json_configuration.c
  src/libpgexporter/utils.c
  src/libpgexporter/yaml_configuration.c
  src/main.c
Labels: feature
