Repository pgexporter/pgexporter, pull requests merged in 2025-08, with the labels that each got.

#289 [#288] Metric_name warning
  src/libpgexporter/json_configuration.c
  src/libpgexporter/yaml_configuration.c
Labels: bug

#287 Add metrics for pgvector
  extensions/vector.yaml
Labels: feature

#305 Use PROMETHEUS_LENGTH
  src/include/pgexporter.h
  src/include/queries.h
  src/libpgexporter/json_configuration.c
  src/libpgexporter/prometheus.c
  src/libpgexporter/prometheus_client.c
  src/libpgexporter/queries.c
  src/libpgexporter/yaml_configuration.c
Labels: enhancement

#300 Add metrics for tracking vacuum
  contrib/json/postgresql-13.json
  contrib/json/postgresql-14.json
  contrib/json/postgresql-15.json
  contrib/json/postgresql-16.json
  contrib/json/postgresql-17.json
  contrib/yaml/postgresql-13.yaml
  contrib/yaml/postgresql-14.yaml
  contrib/yaml/postgresql-15.yaml
  contrib/yaml/postgresql-16.yaml
  contrib/yaml/postgresql-17.yaml
  doc/manual/en/06-prometheus.md
  src/include/internal.h
Labels: feature

#306 Add bloat estimation metric
  contrib/json/postgresql-13.json
  contrib/json/postgresql-14.json
  contrib/json/postgresql-15.json
  contrib/json/postgresql-16.json
  contrib/json/postgresql-17.json
  contrib/yaml/postgresql-13.yaml
  contrib/yaml/postgresql-14.yaml
  contrib/yaml/postgresql-15.yaml
  contrib/yaml/postgresql-16.yaml
  contrib/yaml/postgresql-17.yaml
  doc/manual/en/06-prometheus.md
  src/include/internal.h
Labels: feature

#310 [#295] Add verification checks
  src/include/extension.h
  src/include/yaml_configuration.h
  src/libpgexporter/extension.c
  src/libpgexporter/yaml_configuration.c
Labels: feature

#317 [#307] Default response
  src/libpgexporter/prometheus.c
  src/libpgexporter/yaml_configuration.c
Labels: feature
